"""empty message

Revision ID: 04b9331e465e
Revises: af7138df6a76
Create Date: 2018-10-15 16:54:59.664570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04b9331e465e'
down_revision = 'af7138df6a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glass',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glass_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('thick', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=64), nullable=False),
    sa.Column('img_src', sa.String(length=240), nullable=True),
    sa.Column('glass_count', sa.Float(), nullable=True),
    sa.Column('article', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glass_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glass_type')
    op.drop_table('glass_option')
    op.drop_table('glass')
    # ### end Alembic commands ###
