"""empty message

Revision ID: 0e5120bf7d90
Revises: eeadc0738f5b
Create Date: 2018-10-16 10:55:38.698097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0e5120bf7d90'
down_revision = 'eeadc0738f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glass', 'formula_name')
    op.add_column('good', sa.Column('formula_name', sa.String(length=240), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('good', 'formula_name')
    op.add_column('glass', sa.Column('formula_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=240), nullable=True))
    # ### end Alembic commands ###
