"""empty message

Revision ID: 29ee951ff6b8
Revises: 04b9331e465e
Create Date: 2018-10-15 16:55:40.630963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ee951ff6b8'
down_revision = '04b9331e465e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glass_cat',
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('glass_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['glass_option_id'], ['glass_option.id'], )
    )
    op.add_column('glass', sa.Column('glass_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'glass', 'glass_type', ['glass_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'glass', type_='foreignkey')
    op.drop_column('glass', 'glass_type_id')
    op.drop_table('glass_cat')
    # ### end Alembic commands ###
