"""добавил описание для страниц

Revision ID: 2ce7bacfece6
Revises: e941a23db1af
Create Date: 2019-01-14 01:48:54.725909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce7bacfece6'
down_revision = 'e941a23db1af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_img_containers', sa.Column('alt', sa.Text(), nullable=True))
    op.add_column('article_img_containers', sa.Column('cont_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article_img_containers', 'article_container', ['cont_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article_img_containers', type_='foreignkey')
    op.drop_column('article_img_containers', 'cont_id')
    op.drop_column('article_img_containers', 'alt')
    # ### end Alembic commands ###
