"""add pages

Revision ID: 3301ee2f43ac
Revises: cbb6e0bad077
Create Date: 2019-01-12 18:12:43.668954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3301ee2f43ac'
down_revision = 'cbb6e0bad077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_name', sa.Text(), nullable=True),
    sa.Column('page_transcription', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['article_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cont_id', sa.Integer(), nullable=True),
    sa.Column('src', sa.Text(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cont_id'], ['article_container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cont_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cont_id'], ['article_container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_text')
    op.drop_table('article_img')
    op.drop_table('article_container')
    op.drop_table('article_pages')
    # ### end Alembic commands ###
