"""empty message

Revision ID: 5845f5ad19ac
Revises: 
Create Date: 2018-10-15 16:45:57.687750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5845f5ad19ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('img_src', sa.String(length=240), nullable=False),
    sa.Column('general_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('common_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('menu_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('src', sa.String(length=240), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('general_point_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['general_point_id'], ['menu_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treetment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treetment_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('article', sa.String(length=60), nullable=True),
    sa.Column('treetment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['treetment_id'], ['treetment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treetment_option')
    op.drop_table('treetment')
    op.drop_table('menu_points')
    op.drop_table('common_props')
    op.drop_table('category')
    # ### end Alembic commands ###
