"""empty message

Revision ID: 801e9ca43556
Revises: 29ee951ff6b8
Create Date: 2018-10-15 16:56:24.018577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801e9ca43556'
down_revision = '29ee951ff6b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glass_option', sa.Column('glass_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'glass_option', 'glass', ['glass_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'glass_option', type_='foreignkey')
    op.drop_column('glass_option', 'glass_id')
    # ### end Alembic commands ###
