"""не большие изменения со статьями

Revision ID: 86e60f8d0804
Revises: e8adb8c98188
Create Date: 2019-01-13 22:07:26.111329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e60f8d0804'
down_revision = 'e8adb8c98188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_pages', sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article_pages', 'date')
    # ### end Alembic commands ###
