"""empty message

Revision ID: af7138df6a76
Revises: f0ca2f8faa4c
Create Date: 2018-10-15 16:53:27.041077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af7138df6a76'
down_revision = 'f0ca2f8faa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('good_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['good.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('good', sa.Column('default_option_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'good', 'good_option', ['default_option_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'good', type_='foreignkey')
    op.drop_column('good', 'default_option_id')
    op.drop_table('good_option')
    # ### end Alembic commands ###
