"""empty message

Revision ID: e5b730a0e84e
Revises: 801e9ca43556
Create Date: 2018-10-15 17:26:30.677001

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5b730a0e84e'
down_revision = '801e9ca43556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('good_ibfk_2', 'good', type_='foreignkey')
    op.drop_column('good', 'default_option_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('good', sa.Column('default_option_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('good_ibfk_2', 'good', 'good_option', ['default_option_id'], ['id'])
    # ### end Alembic commands ###
