"""исправил базу

Revision ID: e8adb8c98188
Revises: 3301ee2f43ac
Create Date: 2019-01-13 19:38:31.783431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8adb8c98188'
down_revision = '3301ee2f43ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_img_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cont_id', sa.Integer(), nullable=True),
    sa.Column('alt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cont_id'], ['article_container.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article_img', sa.Column('article_img_container_id', sa.Integer(), nullable=True))
    op.alter_column('article_img', 'src',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=False)
    op.drop_constraint('article_img_ibfk_1', 'article_img', type_='foreignkey')
    op.create_foreign_key(None, 'article_img', 'article_img_containers', ['article_img_container_id'], ['id'])
    op.drop_column('article_img', 'cont_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_img', sa.Column('cont_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'article_img', type_='foreignkey')
    op.create_foreign_key('article_img_ibfk_1', 'article_img', 'article_container', ['cont_id'], ['id'])
    op.alter_column('article_img', 'src',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               nullable=True)
    op.drop_column('article_img', 'article_img_container_id')
    op.drop_table('article_img_containers')
    # ### end Alembic commands ###
