"""добавил описание для страниц

Revision ID: e941a23db1af
Revises: 4541dae90719
Create Date: 2019-01-14 01:47:58.008565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e941a23db1af'
down_revision = '4541dae90719'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('article_img_containers_ibfk_1', 'article_img_containers', type_='foreignkey')
    op.drop_column('article_img_containers', 'alt')
    op.drop_column('article_img_containers', 'cont_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article_img_containers', sa.Column('cont_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('article_img_containers', sa.Column('alt', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True))
    op.create_foreign_key('article_img_containers_ibfk_1', 'article_img_containers', 'article_container', ['cont_id'], ['id'])
    # ### end Alembic commands ###
